server:
  port: 8088
spring:
  datasource:
    url: jdbc:h2:~/mydb  # 数据库
    driver-class-name: org.h2.Driver
    username: root
    password: test
  h2:
    console:
      path: /h2-console  #h2嵌入式数据库控制台，可以通过浏览器访问
      enabled: true
  thymeleaf:
  cache: false
  enabled: true
  prefix: classpath:/templates/
  suffix: .html